### ISSUE TITLE
[Bug] Adding multiple clients / custom client name not working

### ISSUE THREAD

**Issue by Iguana9999phil** [nuxencs/seasonpackarr#113]
### Version

v0.6.0

### Description

I've change my setup from using 1 default client to 2 to separate HD, 4K and the preImportPaths etc. 

Keep on getting `"error":"client not found in config"` and not sure where I need to look.

If I name the default to anything else than default it also gives the same error.

clients:
  qbitsonarr:
    host: "qbit"
    port: 8080
    username: "admin"
    password: "####"
    preImportPath: "/downloads/sonarr"
  qbitsonarr4k:
    host: "qbit"
    port: 8080
    username: "admin"
    password: "####"
    preImportPath: "/downloads/sonarr4k"

### Expected Behavior

Seasonpackarr should be able to match the correct client names.

### Relevant log output

```shell
{"level":"error","module":"processor","release":"REDACTED","clientname":"qbitsonarr4k","error":"client not found in config","time":"2024-05-15T13:43:53Z","message":"error processing season pack: 472"}
```

**Comment by nuxencs** [comment]
@Iguana9999phil did you figure out the issue yourself?

**Comment by Iguana9999phil** [comment]
No but it suddenly started to work, so I'm not sure what I did wrong. Can be removed though all good now.
