### ISSUE TITLE
[Feature Request] Add Version to Docker Container

### ISSUE THREAD

**Issue by bakerboy448** [nuxencs/seasonpackarr#141]
### Description

```
28/49: Container seasonpackarr: update available (Current version: develop)
27/49: Container sabnzbd: up to date (4.3.3-ls180)
26/49: Container readarraudio: up to date (0.4.0.2593-ls334)
```

change dockerfile to include version #

**Comment by nuxencs** [comment]
The docker container has the version, unless you are running the `develop` tag

**Comment by nuxencs** [comment]
as you can see here in the build info for v0.10.0
https://github.com/nuxencs/seasonpackarr/actions/runs/10776037583#summary-29881870344
and for develop
https://github.com/nuxencs/seasonpackarr/actions/runs/10816246651#summary-30007048243

**Comment by bakerboy448** [comment]
change it to be the VERSION and add the commit hash as a develop version?

i.e. `v0.10.0-develop-d60da028`

**Comment by nuxencs** [comment]
hmm good suggestion, let me take a look at how to make that work
