### ISSUE TITLE
[Feature Request] Windows support

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [nuxencs/seasonpackarr#152]
### Description

Windows support.

**Comment by nuxencs** [comment]
What exactly do you mean with windows support?

**Comment by CapivaraTupiniquim** [comment]
I'm not an advanced user, so I don't know how to create an executable with these files provided, nor with the tutorial for Linux. Usually it provides the .exe for windows or it is a .py script to run cross-platform. Sorry for my ignorance.

**Comment by nuxencs** [comment]
there is an .exe for windows 😄 
https://github.com/nuxencs/seasonpackarr/releases/tag/v0.10.1
the zip file called `windows` contains it

**Comment by CapivaraTupiniquim** [comment]
Wow! For some reason it went unnoticed. Thanks!
