### ISSUE TITLE
feat(api): implement smartMode

### ISSUE THREAD

**Issue by nuxencs** [nuxencs/seasonpackarr#22]
implement `smartMode` and `smartThreshold` that will only forward the season pack if there are enough episodes of the same group in qbit already. maybe use [tvmaze api](https://www.tvmaze.com/api) or [sonarr api](https://sonarr.tv/docs/api/#/) to get the total amount of episodes in a specific season

### Example:
smartMode true
smartThreshold 75%
Season Pack with 12 Episodes

FLUX 12 Episodes in qBit
NTb 7 Episodes in qBit

only forward the FLUX pack to qBit

**Comment by chriscla** [comment]
I think you could also check the files that are in the season pack torrent

**Comment by nuxencs** [comment]
> I think you could also check the files that are in the season pack torrent

also sounds like a good idea, but that would require me to always download the .torrent file which I would like to avoid
